### ISSUE TITLE
Broken XML prevents playback

### ISSUE THREAD

**Issue by eknee64** [123Venom/repository.venom#2]
Some TV series in the library - Rick and Morty is a good example - breaks the XML screen so selecting a source results in no playback or errors.

In the XML, when this happens, the right side column below "View Uncashed Torrents" displays only the letter m. There is no rating, date, or episode information.

Kodi build 19.1.0
venom version 6.0.7
Skin is estuary

Thank you for your hard work. Venom is an awesome add  on.

**Comment by 123Venom** [comment]
I just added this show to library and did not have a lick of issue with it.
<img width="1114" alt="Rick and Morty1" src="https://user-images.githubusercontent.com/46383815/126381441-38a2a633-1041-4393-8a42-5d3c6adc0c01.PNG">

Post a screenshot.  Sounds like meta is missing to display the info in the xml.  I will say the runtime is something I can not fix.  For some odd reason pulling runtime from the Kodi library returns values for Movies only, doing so for Shows/Episodes always returns `0` and I've not found a reason for it.  That missing does not break anything so should not be any form of issue to this.

what device?  Post a venom.log also.

**Comment by eknee64** [comment]
I'm using a Mi Android TV box 



Eric Knee

**Comment by 123Venom** [comment]
Added to library via Venom or TMDB Helper?
Also Venom has option to write the .strm files in TMDB Helper format, is that enabled?
Post a venom.log
screenshot to please

**Comment by eknee64** [comment]
Eric Knee

> On Jul 21, 2021, at 5:28 PM, 123Venom ***@***.***> wrote:
> 
> ﻿
> Added to library via Venom or TMDB Helper?
> 
Venom 
> Also Venom has option to write the .strm files in TMDB Helper format, is that enabled?
> 
No
> Post a venom.log
> 
I'm sorry, I don't know where the venom log is.

**Comment by eknee64** [comment]
I found it



Eric Knee

**Comment by 123Venom** [comment]
no log provided
